# Default values for GoApp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: harisahmed001/golang-automation:latest
  pullPolicy: Always

app:
  label: go-app

container:
  name: goapp

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  protocol: TCP
  name: go-svc